permalink: /articles/:title/
exclude:
 - Gemfile
 - Gemfile.lock
include:
 - _AudioChart.spec.js
gems:
 - jekyll-feed
 - jekyll-sitemap

# GitHub defaults
highlighter: rouge
#safe: true -- only way to test plugins locally is to not have this
lsi: false
