permalink: /articles/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - node_modules/
  - package.json
  - package-lock.json
  - talks/2016/audiochart/vendor/get-vendor-libs.sh
  - talks/2016/audiochart/vendor/impress.js-repo/
  - talks/2016/audiochart/vendor/qwerty-hancock-repo/
include:
  - _AudioChart.spec.js
plugins:
  - jekyll-feed
  - jekyll-sitemap

# GitHub defaults
highlighter: rouge
#safe: true -- only way to test plugins locally is to not have this
lsi: false
